using System.Security.Cryptography;
using System.Text;
using Launcher.Models.Profiles;

namespace Launcher.Scripts.Templates;

public sealed record CodexChatTemplateCompatibilityResult(
    ModelProfile Profile,
    bool TemplateGenerated);

/// <summary>
/// Creates a model-owned llama.cpp chat-template override only when the GGUF's
/// embedded template contains the known strict Qwen guard that rejects Codex
/// system messages after the first turn. Request and response bodies remain
/// untouched; llama.cpp still performs all template rendering and inference.
/// </summary>
public static class CodexChatTemplateCompatibility
{
    public const string OwnershipMarker =
        "{# Generated by ChatGPT Local Launcher from the model's embedded chat template. DO NOT EDIT. #}";

    private const uint GgufMagic = 0x46554747;
    private const int MaximumMetadataKeyBytes = 16 * 1024;
    private const int MaximumChatTemplateBytes = 1024 * 1024;
    private const ulong MaximumMetadataEntries = 1_000_000;
    private const ulong MaximumArrayElements = 10_000_000;

    private const string StrictSystemGuard = """
        {%- if not loop.first %}
            {{- raise_exception('System message must be at the beginning.') }}
        {%- endif %}
""";

    private const string CompatibleSystemGuard = """
        {%- if not loop.first %}
            {{- '<|im_start|>system\n' + content + '<|im_end|>' + '\n' }}
        {%- endif %}
""";

    public static async Task<CodexChatTemplateCompatibilityResult> EnsureAsync(
        ModelProfile profile,
        string runtimeRoot,
        CancellationToken cancellationToken = default,
        string? templateFileName = null)
    {
        ArgumentNullException.ThrowIfNull(profile);
        ArgumentException.ThrowIfNullOrWhiteSpace(runtimeRoot);

        if (!profile.Jinja || !string.IsNullOrWhiteSpace(profile.ChatTemplateRelativePath))
        {
            return new CodexChatTemplateCompatibilityResult(profile, TemplateGenerated: false);
        }

        var root = Path.GetFullPath(runtimeRoot);
        var modelPath = Path.GetFullPath(Path.Combine(root, profile.ModelRelativePath));
        var embeddedTemplate = ReadEmbeddedChatTemplate(modelPath, cancellationToken);
        if (!TryCreateCompatibleTemplate(embeddedTemplate, out var compatibleTemplate))
        {
            return new CodexChatTemplateCompatibilityResult(profile, TemplateGenerated: false);
        }

        var sourceTemplate = embeddedTemplate!;
        if (templateFileName is not null && (Path.GetFileName(templateFileName) != templateFileName
            || !templateFileName.EndsWith(".jinja", StringComparison.OrdinalIgnoreCase)))
            throw new ArgumentException("模板文件名无效。", nameof(templateFileName));

        var relativeTemplatePath = Path.Combine(
            "scripts",
            "templates",
            templateFileName ?? profile.Id + ".codex-compatible.jinja");
        var outputPath = Path.GetFullPath(Path.Combine(root, relativeTemplatePath));
        var expectedPrefix = root.TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar)
            + Path.DirectorySeparatorChar;
        if (!outputPath.StartsWith(expectedPrefix, StringComparison.OrdinalIgnoreCase))
        {
            throw new InvalidDataException("生成的 Chat Template 路径逃逸 Runtime Root。");
        }

        var output = CreateOwnedOutput(sourceTemplate, compatibleTemplate);
        await WriteOwnedAtomicallyAsync(outputPath, output, cancellationToken, sourceTemplate).ConfigureAwait(false);
        var backupPath = Path.Combine(root, "scripts", "templates", profile.Id + ".embedded.jinja");
        await WriteOwnedAtomicallyAsync(backupPath, CreateOwnedOutput(sourceTemplate, sourceTemplate), cancellationToken).ConfigureAwait(false);

        var updatedDefaults = profile.DefaultParameters is null
            ? null
            : profile.DefaultParameters with { ChatTemplateRelativePath = relativeTemplatePath };
        var updatedProfile = profile with
        {
            ChatTemplateRelativePath = relativeTemplatePath,
            DefaultParameters = updatedDefaults,
        };
        return new CodexChatTemplateCompatibilityResult(updatedProfile, TemplateGenerated: true);
    }

    public static string? ReadEmbeddedChatTemplate(
        string modelPath,
        CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(modelPath);
        using var stream = new FileStream(
            Path.GetFullPath(modelPath),
            FileMode.Open,
            FileAccess.Read,
            FileShare.Read,
            bufferSize: 64 * 1024,
            FileOptions.SequentialScan);
        using var reader = new BinaryReader(stream, Encoding.UTF8, leaveOpen: false);

        if (reader.ReadUInt32() != GgufMagic)
        {
            throw new InvalidDataException("模型不是有效的 GGUF 文件。");
        }

        var version = reader.ReadUInt32();
        if (version is not (2 or 3))
        {
            throw new InvalidDataException($"暂不支持读取 GGUF v{version} 元数据。");
        }

        _ = reader.ReadUInt64(); // tensor count
        var metadataCount = reader.ReadUInt64();
        if (metadataCount > MaximumMetadataEntries)
        {
            throw new InvalidDataException("GGUF 元数据条目数异常。");
        }

        for (ulong index = 0; index < metadataCount; index++)
        {
            cancellationToken.ThrowIfCancellationRequested();
            var key = ReadString(reader, MaximumMetadataKeyBytes, "GGUF 元数据键");
            var valueType = ReadValueType(reader);
            if (string.Equals(key, "tokenizer.chat_template", StringComparison.Ordinal))
            {
                if (valueType != GgufValueType.String)
                {
                    throw new InvalidDataException("GGUF tokenizer.chat_template 不是字符串。");
                }

                return ReadString(reader, MaximumChatTemplateBytes, "GGUF Chat Template");
            }

            SkipValue(reader, valueType, cancellationToken);
        }

        return null;
    }

    public static bool TryCreateCompatibleTemplate(string? embeddedTemplate, out string compatibleTemplate)
    {
        var analysis = ChatTemplateRules.Analyze(embeddedTemplate);
        compatibleTemplate = analysis.RepairedTemplate ?? string.Empty;
        return analysis.Kind == ChatTemplateMatchKind.Repairable;
    }

    public static string CreateOwnedOutput(string sourceTemplate, string template)
    {
        var analysis = ChatTemplateRules.Analyze(sourceTemplate);
        var sourceHash = ChatTemplateValidationCache.Hash(sourceTemplate);
        var payload = template.TrimStart('\uFEFF');
        if (!payload.EndsWith('\n')) payload += "\n";
        return OwnershipMarker + "\n"
            + $"{{# Embedded template SHA-256: {sourceHash} #}}\n"
            + $"{{# Compatibility rule: {analysis.RuleId ?? "none"}:{analysis.RuleVersion} #}}\n"
            + $"{{# Template body SHA-256: {ChatTemplateValidationCache.Hash(payload)} #}}\n"
            + payload;
    }

    private static async Task WriteOwnedAtomicallyAsync(
        string path,
        string content,
        CancellationToken cancellationToken,
        string? sourceTemplate = null)
    {
        var directory = Path.GetDirectoryName(path)
            ?? throw new InvalidOperationException("Chat Template 必须位于一个目录中。");
        Directory.CreateDirectory(directory);

        if (File.Exists(path))
        {
            string? firstLine;
            using (var reader = new StreamReader(path, Encoding.UTF8, detectEncodingFromByteOrderMarks: true))
            {
                firstLine = await reader.ReadLineAsync(cancellationToken).ConfigureAwait(false);
            }

            if (!string.Equals(firstLine, OwnershipMarker, StringComparison.Ordinal))
            {
                throw new InvalidDataException($"拒绝覆盖无法确认归属的 Chat Template：{path}");
            }

            var existing = await File.ReadAllTextAsync(path, cancellationToken).ConfigureAwait(false);
            if (string.Equals(existing, content, StringComparison.Ordinal))
            {
                return;
            }
            if (!IsUnmodifiedOwnedOutput(existing, sourceTemplate))
                throw new InvalidDataException($"拒绝覆盖已修改或无法验证的 Chat Template：{path}");
        }

        var temporaryPath = Path.Combine(directory, $".{Path.GetFileName(path)}.{Guid.NewGuid():N}.tmp");
        try
        {
            await File.WriteAllTextAsync(
                temporaryPath,
                content,
                new UTF8Encoding(encoderShouldEmitUTF8Identifier: false),
                cancellationToken).ConfigureAwait(false);
            File.Move(temporaryPath, path, overwrite: true);
        }
        finally
        {
            try
            {
                File.Delete(temporaryPath);
            }
            catch (Exception exception) when (exception is IOException or UnauthorizedAccessException)
            {
                // Preserve the original write result; temp templates are never referenced.
            }
        }
    }

    public static bool IsUnmodifiedOwnedOutput(string text, string? sourceTemplate = null)
    {
        if (!text.StartsWith(OwnershipMarker + "\n", StringComparison.Ordinal)) return false;
        const string hashPrefix = "{# Template body SHA-256: ";
        var lines = text.Split('\n');
        if (lines.Length > 4 && lines[3].StartsWith(hashPrefix, StringComparison.Ordinal) && lines[3].EndsWith(" #}", StringComparison.Ordinal))
        {
            var declared = lines[3][hashPrefix.Length..^3];
            return declared == ChatTemplateValidationCache.Hash(string.Join('\n', lines.Skip(4)));
        }
        // Legacy files have only a source hash. Reconstruct the old exact transformation
        // from the same GGUF before allowing an upgrade; a marker alone proves no integrity.
        if (sourceTemplate is null) return false;
        var normalized = sourceTemplate.Replace("\r\n", "\n", StringComparison.Ordinal);
        var legacy = normalized.Replace(StrictSystemGuard, CompatibleSystemGuard, StringComparison.Ordinal).TrimStart('\uFEFF');
        if (!legacy.EndsWith('\n')) legacy += "\n";
        return text == OwnershipMarker + "\n" + $"{{# Embedded template SHA-256: {ChatTemplateValidationCache.Hash(sourceTemplate)} #}}\n" + legacy;
    }

    private static GgufValueType ReadValueType(BinaryReader reader)
    {
        var raw = reader.ReadUInt32();
        if (!Enum.IsDefined(typeof(GgufValueType), raw))
        {
            throw new InvalidDataException($"GGUF 元数据类型无效：{raw}。");
        }

        return (GgufValueType)raw;
    }

    private static string ReadString(BinaryReader reader, int maximumBytes, string fieldName)
    {
        var byteCount = reader.ReadUInt64();
        if (byteCount > (ulong)maximumBytes)
        {
            throw new InvalidDataException($"{fieldName} 超过允许长度。");
        }

        EnsureAvailable(reader.BaseStream, byteCount);
        var bytes = reader.ReadBytes(checked((int)byteCount));
        if ((ulong)bytes.Length != byteCount)
        {
            throw new EndOfStreamException($"{fieldName} 被截断。");
        }

        return Encoding.UTF8.GetString(bytes);
    }

    private static void SkipValue(
        BinaryReader reader,
        GgufValueType valueType,
        CancellationToken cancellationToken)
    {
        if (valueType == GgufValueType.String)
        {
            SkipString(reader);
            return;
        }

        if (valueType == GgufValueType.Array)
        {
            var elementType = ReadValueType(reader);
            if (elementType == GgufValueType.Array)
            {
                throw new InvalidDataException("GGUF 元数据不允许嵌套数组。");
            }

            var elementCount = reader.ReadUInt64();
            if (elementCount > MaximumArrayElements)
            {
                throw new InvalidDataException("GGUF 元数据数组过大。");
            }

            if (elementType == GgufValueType.String)
            {
                for (ulong index = 0; index < elementCount; index++)
                {
                    if ((index & 1023) == 0)
                    {
                        cancellationToken.ThrowIfCancellationRequested();
                    }

                    SkipString(reader);
                }

                return;
            }

            var elementSize = ScalarSize(elementType);
            SeekForward(reader.BaseStream, checked(elementCount * (ulong)elementSize));
            return;
        }

        SeekForward(reader.BaseStream, (ulong)ScalarSize(valueType));
    }

    private static void SkipString(BinaryReader reader)
    {
        var byteCount = reader.ReadUInt64();
        SeekForward(reader.BaseStream, byteCount);
    }

    private static int ScalarSize(GgufValueType valueType) => valueType switch
    {
        GgufValueType.UInt8 or GgufValueType.Int8 or GgufValueType.Bool => 1,
        GgufValueType.UInt16 or GgufValueType.Int16 => 2,
        GgufValueType.UInt32 or GgufValueType.Int32 or GgufValueType.Float32 => 4,
        GgufValueType.UInt64 or GgufValueType.Int64 or GgufValueType.Float64 => 8,
        _ => throw new InvalidDataException($"GGUF 标量类型无效：{valueType}。"),
    };

    private static void SeekForward(Stream stream, ulong byteCount)
    {
        EnsureAvailable(stream, byteCount);
        stream.Seek(checked((long)byteCount), SeekOrigin.Current);
    }

    private static void EnsureAvailable(Stream stream, ulong byteCount)
    {
        if (stream.Position < 0 || stream.Position > stream.Length)
        {
            throw new EndOfStreamException("GGUF 元数据读取位置无效。");
        }

        var remaining = checked((ulong)(stream.Length - stream.Position));
        if (byteCount > remaining)
        {
            throw new EndOfStreamException("GGUF 元数据被截断。");
        }
    }

    private enum GgufValueType : uint
    {
        UInt8 = 0,
        Int8 = 1,
        UInt16 = 2,
        Int16 = 3,
        UInt32 = 4,
        Int32 = 5,
        Float32 = 6,
        Bool = 7,
        String = 8,
        Array = 9,
        UInt64 = 10,
        Int64 = 11,
        Float64 = 12,
    }
}
