<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Launcher.Core\Launcher.Core.csproj" />
    <ProjectReference Include="..\Launcher.Runtime\Launcher.Runtime.csproj" />
    <ProjectReference Include="..\Launcher.ChatGPT\Launcher.ChatGPT.csproj" />
    <ProjectReference Include="..\Launcher.Models\Launcher.Models.csproj" />
    <ProjectReference Include="..\Launcher.Orchestration\Launcher.Orchestration.csproj" />
    <ProjectReference Include="..\Launcher.Scripts\Launcher.Scripts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <OutputType Condition="'$(Configuration)' == 'Release'">WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
