using System.Globalization;
using System.Text;
using Launcher.Models.Profiles;

namespace Launcher.Scripts.Batch;

public static class BatchScriptGenerator
{
    public const string OwnershipMarker = ":: Generated by ChatGPT Local Launcher. DO NOT EDIT.";

    public static string Generate(ModelProfile profile, string runtimeRoot)
    {
        ArgumentNullException.ThrowIfNull(profile);
        ArgumentException.ThrowIfNullOrWhiteSpace(runtimeRoot);
        var root = Path.GetFullPath(runtimeRoot);
        var errors = ModelProfileValidator.Validate(profile, root);
        if (errors.Count > 0)
        {
            throw new InvalidDataException(string.Join(Environment.NewLine, errors));
        }

        var modelPath = Path.GetFullPath(Path.Combine(root, profile.ModelRelativePath));
        var relativeModelPath = EscapeLiteral(Path.GetRelativePath(root, modelPath));
        var arguments = new List<string>
        {
            $"--model \"%LLAMA_ROOT%\\{relativeModelPath}\"",
            $"--host {QuoteValue(profile.Host)}",
            $"--port {profile.Port.ToString(CultureInfo.InvariantCulture)}",
            $"--alias {QuoteValue(profile.Alias)}",
        };

        if (profile.ContextSize > 0)
        {
            arguments.Add($"--ctx-size {profile.ContextSize.ToString(CultureInfo.InvariantCulture)}");
        }

        arguments.Add($"--n-gpu-layers {QuoteValue(profile.GpuLayers)}");
        if (!string.IsNullOrWhiteSpace(profile.Device))
        {
            arguments.Add($"--device {QuoteValue(profile.Device)}");
        }

        arguments.Add($"--flash-attn {QuoteValue(profile.FlashAttention)}");
        arguments.Add($"--cache-type-k {QuoteValue(profile.CacheTypeK)}");
        arguments.Add($"--cache-type-v {QuoteValue(profile.CacheTypeV)}");
        if (profile.Parallel > 0)
        {
            arguments.Add($"--parallel {profile.Parallel.ToString(CultureInfo.InvariantCulture)}");
        }

        arguments.Add(profile.Jinja ? "--jinja" : "--no-jinja");
        if (!string.IsNullOrWhiteSpace(profile.ChatTemplateRelativePath))
        {
            arguments.Add(
                $"--chat-template-file \"%LLAMA_ROOT%\\{EscapeLiteral(profile.ChatTemplateRelativePath)}\"");
        }

        if (profile.BatchSize is not null)
        {
            arguments.Add($"--batch-size {profile.BatchSize.Value.ToString(CultureInfo.InvariantCulture)}");
        }

        if (profile.MicroBatchSize is not null)
        {
            arguments.Add($"--ubatch-size {profile.MicroBatchSize.Value.ToString(CultureInfo.InvariantCulture)}");
        }

        arguments.Add($"--sleep-idle-seconds {profile.IdleSleepSeconds.ToString(CultureInfo.InvariantCulture)}");

        foreach (var argument in profile.ExtraArguments.OrderBy(pair => pair.Key, StringComparer.Ordinal))
        {
            arguments.Add(argument.Value is null
                ? $"--{argument.Key}"
                : $"--{argument.Key} {QuoteValue(argument.Value)}");
        }

        var builder = new StringBuilder();
        builder.AppendLine("@echo off");
        builder.AppendLine(OwnershipMarker);
        builder.AppendLine("setlocal DisableDelayedExpansion");
        builder.AppendLine("set \"LLAMA_ROOT=%~dp0..\"");
        builder.AppendLine();
        builder.AppendLine("\"%LLAMA_ROOT%\\llama-server.exe\" ^");
        for (var index = 0; index < arguments.Count; index++)
        {
            builder.Append("  ").Append(arguments[index]);
            builder.AppendLine(index == arguments.Count - 1 ? string.Empty : " ^");
        }

        builder.AppendLine();
        builder.AppendLine("exit /b %ERRORLEVEL%");
        return builder.ToString().Replace("\n", "\r\n", StringComparison.Ordinal).Replace("\r\r\n", "\r\n", StringComparison.Ordinal);
    }

    public static void EnsureCanWrite(string runtimeRoot, string profileId)
    {
        var path = GetOutputPath(runtimeRoot, profileId);
        if (!File.Exists(path))
        {
            return;
        }

        using var reader = new StreamReader(path, Encoding.UTF8, detectEncodingFromByteOrderMarks: true);
        var firstLine = reader.ReadLine();
        var secondLine = reader.ReadLine();
        if (!string.Equals(firstLine, "@echo off", StringComparison.OrdinalIgnoreCase)
            || !string.Equals(secondLine, OwnershipMarker, StringComparison.Ordinal))
        {
            throw new BatchScriptOwnershipException(
                $"拒绝覆盖无法确认归属的脚本：{path}");
        }
    }

    public static async Task<string> WriteOwnedAsync(
        string runtimeRoot,
        ModelProfile profile,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(profile);
        var path = GetOutputPath(runtimeRoot, profile.Id);
        EnsureCanWrite(runtimeRoot, profile.Id);
        var directory = Path.GetDirectoryName(path)
            ?? throw new InvalidOperationException("BAT 输出路径必须位于目录中。");
        Directory.CreateDirectory(directory);
        var temporaryPath = Path.Combine(directory, $".{profile.Id}.{Guid.NewGuid():N}.tmp");
        try
        {
            await File.WriteAllTextAsync(
                temporaryPath,
                Generate(profile, runtimeRoot),
                new UTF8Encoding(encoderShouldEmitUTF8Identifier: false),
                cancellationToken).ConfigureAwait(false);
            File.Move(temporaryPath, path, overwrite: true);
            return path;
        }
        finally
        {
            try
            {
                File.Delete(temporaryPath);
            }
            catch (Exception exception) when (exception is IOException or UnauthorizedAccessException)
            {
                // Preserve the original write result; temp files are never executed.
            }
        }
    }

    public static string GetOutputPath(string runtimeRoot, string profileId)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(runtimeRoot);
        ArgumentException.ThrowIfNullOrWhiteSpace(profileId);
        if (profileId.IndexOfAny(Path.GetInvalidFileNameChars()) >= 0
            || profileId is "." or ".."
            || profileId.Contains(Path.DirectorySeparatorChar)
            || profileId.Contains(Path.AltDirectorySeparatorChar))
        {
            throw new ArgumentException("Profile ID 不能用作 BAT 文件名。", nameof(profileId));
        }

        return Path.Combine(Path.GetFullPath(runtimeRoot), "scripts", profileId + ".bat");
    }

    public static void DeleteOwned(string runtimeRoot, string profileId)
    {
        var path = GetOutputPath(runtimeRoot, profileId);
        if (!File.Exists(path))
        {
            return;
        }

        EnsureCanWrite(runtimeRoot, profileId);
        File.Delete(path);
    }

    private static string QuoteValue(string value)
    {
        if (value.IndexOfAny(['\0', '\r', '\n', '"']) >= 0)
        {
            throw new InvalidDataException("BAT 参数包含无法安全转义的字符。");
        }

        return $"\"{EscapeLiteral(value)}\"";
    }

    private static string EscapeLiteral(string value) => value.Replace("%", "%%", StringComparison.Ordinal);
}
